SELECT * FROM Customer

BEGIN TRANSACTION
DELETE FROM Customer
WHERE CustomerName= 'Alex'
ROLLBACK

BEGIN TRANSACTION
DELETE FROM Customer
WHERE CustomerPhone ='056547594'
COMMIT

BEGIN TRANSACTION
DELETE FROM Customer
WHERE CustomerAddress = 'Jalan Melati'
COMMIT

BEGIN TRANSACTION
DELETE FROM Customer
WHERE CustomerPhone ='123456789'
COMMIT

BEGIN TRANSACTION
DELETE FROM Customer
WHERE CustomerName ='Alexa'
COMMIT

SELECT * FROM HeaderSellTransaction

BEGIN TRANSACTION
DELETE FROM HeaderSellTransaction
WHERE DATENAME(DAY,TransactionDate) = 21
ROLLBACK